import type { CanonList } from './types'

/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from docs/playlists/*.md by scripts/convert-playlists.ts
 * Run: npm run generate:canon-lists
 */

export const AFI: CanonList = {
  id: 'afi',
  title: "AFI’S 100 YEARS…100 MOVIES",
  shortTitle: "AFI’S 100 YEARS…100 MOVIES",
  sourceUrl: "https://letterboxd.com/afi/list/afis-100-years100-movies-10th-anniversary/detail/",
  totalMovies: 100,
  movies: [
  { title: "Citizen Kane", year: 1941 },
  { title: "The Godfather", year: 1972 },
  { title: "Casablanca", year: 1942 },
  { title: "Raging Bull", year: 1980 },
  { title: "Singin’ in the Rain", year: 1952 },
  { title: "Gone with the Wind", year: 1939 },
  { title: "Lawrence of Arabia", year: 1962 },
  { title: "Schindler’s List", year: 1993 },
  { title: "Vertigo", year: 1958 },
  { title: "The Wizard of Oz", year: 1939 },
  { title: "City Lights", year: 1931 },
  { title: "The Searchers", year: 1956 },
  { title: "Star Wars", year: 1977 },
  { title: "Psycho", year: 1960 },
  { title: "2001: A Space Odyssey", year: 1968 },
  { title: "Sunset Boulevard", year: 1950 },
  { title: "The Graduate", year: 1967 },
  { title: "The General", year: 1926 },
  { title: "On the Waterfront", year: 1954 },
  { title: "It’s a Wonderful Life", year: 1946 },
  { title: "Chinatown", year: 1974 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "The Grapes of Wrath", year: 1940 },
  { title: "E.T. the Extra-Terrestrial", year: 1982 },
  { title: "To Kill a Mockingbird", year: 1962 },
  { title: "Mr. Smith Goes to Washington", year: 1939 },
  { title: "High Noon", year: 1952 },
  { title: "All About Eve", year: 1950 },
  { title: "Double Indemnity", year: 1944 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "The Maltese Falcon", year: 1941 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "One Flew Over the Cuckoo’s Nest", year: 1975 },
  { title: "Snow White and the Seven Dwarfs", year: 1937 },
  { title: "Annie Hall", year: 1977 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "The Best Years of Our Lives", year: 1946 },
  { title: "The Treasure of the Sierra Madre", year: 1948 },
  { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964 },
  { title: "The Sound of Music", year: 1965 },
  { title: "King Kong", year: 1933 },
  { title: "Bonnie and Clyde", year: 1967 },
  { title: "Midnight Cowboy", year: 1969 },
  { title: "The Philadelphia Story", year: 1940 },
  { title: "Shane", year: 1953 },
  { title: "It Happened One Night", year: 1934 },
  { title: "A Streetcar Named Desire", year: 1951 },
  { title: "Rear Window", year: 1954 },
  { title: "Intolerance: Love’s Struggle Throughout the Ages", year: 1916 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "West Side Story", year: 1961 },
  { title: "Taxi Driver", year: 1976 },
  { title: "The Deer Hunter", year: 1978 },
  { title: "M*A*S*H", year: 1970 },
  { title: "North by Northwest", year: 1959 },
  { title: "Jaws", year: 1975 },
  { title: "Rocky", year: 1976 },
  { title: "The Gold Rush", year: 1925 },
  { title: "Nashville", year: 1975 },
  { title: "Duck Soup", year: 1933 },
  { title: "Sullivan’s Travels", year: 1941 },
  { title: "American Graffiti", year: 1973 },
  { title: "Cabaret", year: 1972 },
  { title: "Network", year: 1976 },
  { title: "The African Queen", year: 1951 },
  { title: "Raiders of the Lost Ark", year: 1981 },
  { title: "Who’s Afraid of Virginia Woolf?", year: 1966 },
  { title: "Unforgiven", year: 1992 },
  { title: "Tootsie", year: 1982 },
  { title: "A Clockwork Orange", year: 1971 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "Butch Cassidy and the Sundance Kid", year: 1969 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "In the Heat of the Night", year: 1967 },
  { title: "Forrest Gump", year: 1994 },
  { title: "All the President’s Men", year: 1976 },
  { title: "Modern Times", year: 1936 },
  { title: "The Wild Bunch", year: 1969 },
  { title: "The Apartment", year: 1960 },
  { title: "Spartacus", year: 1960 },
  { title: "Sunrise: A Song of Two Humans", year: 1927 },
  { title: "Titanic", year: 1997 },
  { title: "Easy Rider", year: 1969 },
  { title: "A Night at the Opera", year: 1935 },
  { title: "Platoon", year: 1986 },
  { title: "12 Angry Men", year: 1957 },
  { title: "Bringing Up Baby", year: 1938 },
  { title: "The Sixth Sense", year: 1999 },
  { title: "Swing Time", year: 1936 },
  { title: "Sophie’s Choice", year: 1982 },
  { title: "GoodFellas", year: 1990 },
  { title: "The French Connection", year: 1971 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "The Last Picture Show", year: 1971 },
  { title: "Do the Right Thing", year: 1989 },
  { title: "Blade Runner", year: 1982 },
  { title: "Yankee Doodle Dandy", year: 1942 },
  { title: "Toy Story", year: 1995 },
  { title: "Ben-Hur", year: 1959 }
  ]
}

export const CANNES_PALME: CanonList = {
  id: 'cannes_palme',
  title: "Cannes Palme d’Or Winners",
  shortTitle: "Cannes Palme d’Or Winners",
  sourceUrl: "https://letterboxd.com/brsan/list/cannes-palme-dor-winners/",
  totalMovies: 103,
  movies: [
  { title: "It Was Just an Accident", year: 2025 },
  { title: "Anora", year: 2024 },
  { title: "Anatomy of a Fall", year: 2023 },
  { title: "Triangle of Sadness", year: 2022 },
  { title: "Titane", year: 2021 },
  { title: "Parasite", year: 2019 },
  { title: "Shoplifters", year: 2018 },
  { title: "The Image Book", year: 2018 },
  { title: "The Square", year: 2017 },
  { title: "I, Daniel Blake", year: 2016 },
  { title: "Dheepan", year: 2015 },
  { title: "Winter Sleep", year: 2014 },
  { title: "Blue Is the Warmest Color", year: 2013 },
  { title: "Amour", year: 2012 },
  { title: "The Tree of Life", year: 2011 },
  { title: "Uncle Boonmee Who Can Recall His Past Lives", year: 2010 },
  { title: "The White Ribbon", year: 2009 },
  { title: "The Class", year: 2008 },
  { title: "4 Months, 3 Weeks and 2 Days", year: 2007 },
  { title: "The Wind That Shakes the Barley", year: 2006 },
  { title: "The Child", year: 2005 },
  { title: "Fahrenheit 9/11", year: 2004 },
  { title: "Elephant", year: 2003 },
  { title: "The Pianist", year: 2002 },
  { title: "The Son’s Room", year: 2001 },
  { title: "Dancer in the Dark", year: 2000 },
  { title: "Rosetta", year: 1999 },
  { title: "Eternity and a Day", year: 1998 },
  { title: "Taste of Cherry", year: 1997 },
  { title: "The Eel", year: 1997 },
  { title: "Secrets & Lies", year: 1996 },
  { title: "Underground", year: 1995 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "Farewell My Concubine", year: 1993 },
  { title: "The Piano", year: 1993 },
  { title: "The Best Intentions", year: 1992 },
  { title: "Barton Fink", year: 1991 },
  { title: "Wild at Heart", year: 1990 },
  { title: "sex, lies, and videotape", year: 1989 },
  { title: "Pelle the Conqueror", year: 1987 },
  { title: "Under the Sun of Satan", year: 1987 },
  { title: "The Mission", year: 1986 },
  { title: "When Father Was Away on Business", year: 1985 },
  { title: "Paris, Texas", year: 1984 },
  { title: "The Ballad of Narayama", year: 1983 },
  { title: "Missing", year: 1982 },
  { title: "The Road", year: 1982 },
  { title: "Man of Iron", year: 1981 },
  { title: "Kagemusha", year: 1980 },
  { title: "All That Jazz", year: 1979 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "The Tin Drum", year: 1979 },
  { title: "The Tree of Wooden Clogs", year: 1978 },
  { title: "Padre Padrone", year: 1977 },
  { title: "Taxi Driver", year: 1976 },
  { title: "Chronicle of the Years of Fire", year: 1975 },
  { title: "The Conversation", year: 1974 },
  { title: "Scarecrow", year: 1973 },
  { title: "The Hireling", year: 1973 },
  { title: "The Working Class Goes to Heaven", year: 1971 },
  { title: "The Mattei Affair", year: 1972 },
  { title: "The Go-Between", year: 1971 },
  { title: "M*A*S*H", year: 1970 },
  { title: "if…", year: 1968 },
  { title: "Blow-Up", year: 1966 },
  { title: "A Man and a Woman", year: 1966 },
  { title: "The Birds, the Bees and the Italians", year: 1966 },
  { title: "The Knack… and How to Get It", year: 1965 },
  { title: "The Umbrellas of Cherbourg", year: 1964 },
  { title: "The Leopard", year: 1963 },
  { title: "The Given Word", year: 1962 },
  { title: "The Long Absence", year: 1961 },
  { title: "Viridiana", year: 1961 },
  { title: "La Dolce Vita", year: 1960 },
  { title: "Black Orpheus", year: 1959 },
  { title: "The Cranes Are Flying", year: 1957 },
  { title: "Friendly Persuasion", year: 1956 },
  { title: "The Silent World", year: 1956 },
  { title: "Marty", year: 1955 },
  { title: "Gate of Hell", year: 1953 },
  { title: "The Wages of Fear", year: 1953 },
  { title: "Othello", year: 1951 },
  { title: "Two Cents Worth of Hope", year: 1952 },
  { title: "Miracle in Milan", year: 1951 },
  { title: "Miss Julie", year: 1951 },
  { title: "The Third Man", year: 1949 },
  { title: "Antoine & Antoinette", year: 1947 },
  { title: "Crossfire", year: 1947 },
  { title: "The Damned", year: 1947 },
  { title: "Dumbo", year: 1941 },
  { title: "Ziegfeld Follies", year: 1945 },
  { title: "Rome, Open City", year: 1945 },
  { title: "Pastoral Symphony", year: 1946 },
  { title: "Torment", year: 1944 },
  { title: "Men Without Wings", year: 1946 },
  { title: "Red Meadows", year: 1945 },
  { title: "Maria Candelaria", year: 1944 },
  { title: "The Last Chance", year: 1945 },
  { title: "Neecha Nagar", year: 1946 },
  { title: "The Turning Point", year: 1945 },
  { title: "The Lost Weekend", year: 1945 },
  { title: "Brief Encounter", year: 1945 },
  { title: "Union Pacific", year: 1939 }
  ]
}

export const IMDB_TOP_250: CanonList = {
  id: 'imdb_top_250',
  title: "IMDb Top 250",
  shortTitle: "IMDb Top 250",
  sourceUrl: "https://letterboxd.com/dave/list/imdb-top-250/",
  totalMovies: 250,
  movies: [
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "The Godfather", year: 1972 },
  { title: "The Dark Knight", year: 2008 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "12 Angry Men", year: 1957 },
  { title: "The Lord of the Rings: The Return of the King", year: 2003 },
  { title: "Schindler’s List", year: 1993 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "The Good, the Bad and the Ugly", year: 1966 },
  { title: "The Lord of the Rings: The Two Towers", year: 2002 },
  { title: "Forrest Gump", year: 1994 },
  { title: "Fight Club", year: 1999 },
  { title: "Inception", year: 2010 },
  { title: "The Empire Strikes Back", year: 1980 },
  { title: "The Matrix", year: 1999 },
  { title: "GoodFellas", year: 1990 },
  { title: "Interstellar", year: 2014 },
  { title: "One Flew Over the Cuckoo’s Nest", year: 1975 },
  { title: "Se7en", year: 1995 },
  { title: "It’s a Wonderful Life", year: 1946 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "Seven Samurai", year: 1954 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "The Green Mile", year: 1999 },
  { title: "City of God", year: 2002 },
  { title: "Life Is Beautiful", year: 1997 },
  { title: "Terminator 2: Judgment Day", year: 1991 },
  { title: "Star Wars", year: 1977 },
  { title: "Back to the Future", year: 1985 },
  { title: "Spirited Away", year: 2001 },
  { title: "The Pianist", year: 2002 },
  { title: "Gladiator", year: 2000 },
  { title: "Parasite", year: 2019 },
  { title: "Psycho", year: 1960 },
  { title: "Grave of the Fireflies", year: 1988 },
  { title: "The Lion King", year: 1994 },
  { title: "Harakiri", year: 1962 },
  { title: "The Departed", year: 2006 },
  { title: "Whiplash", year: 2014 },
  { title: "The Prestige", year: 2006 },
  { title: "American History X", year: 1998 },
  { title: "Léon: The Professional", year: 1994 },
  { title: "Spider-Man: Across the Spider-Verse", year: 2023 },
  { title: "Cinema Paradiso", year: 1988 },
  { title: "Casablanca", year: 1942 },
  { title: "The Intouchables", year: 2011 },
  { title: "The Usual Suspects", year: 1995 },
  { title: "Alien", year: 1979 },
  { title: "Modern Times", year: 1936 },
  { title: "Rear Window", year: 1954 },
  { title: "Django Unchained", year: 2012 },
  { title: "Once Upon a Time in the West", year: 1968 },
  { title: "City Lights", year: 1931 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "WALL·E", year: 2008 },
  { title: "Memento", year: 2000 },
  { title: "Dune: Part Two", year: 2024 },
  { title: "Raiders of the Lost Ark", year: 1981 },
  { title: "Avengers: Infinity War", year: 2018 },
  { title: "The Lives of Others", year: 2006 },
  { title: "Spider-Man: Into the Spider-Verse", year: 2018 },
  { title: "Sunset Boulevard", year: 1950 },
  { title: "Witness for the Prosecution", year: 1957 },
  { title: "Paths of Glory", year: 1957 },
  { title: "The Shining", year: 1980 },
  { title: "The Great Dictator", year: 1940 },
  { title: "Inglourious Basterds", year: 2009 },
  { title: "12th Fail", year: 2023 },
  { title: "Aliens", year: 1986 },
  { title: "High and Low", year: 1963 },
  { title: "The Dark Knight Rises", year: 2012 },
  { title: "Coco", year: 2017 },
  { title: "Avengers: Endgame", year: 2019 },
  { title: "Good Will Hunting", year: 1997 },
  { title: "Amadeus", year: 1984 },
  { title: "Toy Story", year: 1995 },
  { title: "Your Name.", year: 2016 },
  { title: "Das Boot", year: 1981 },
  { title: "Oldboy", year: 2003 },
  { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964 },
  { title: "Braveheart", year: 1995 },
  { title: "Princess Mononoke", year: 1997 },
  { title: "American Beauty", year: 1999 },
  { title: "3 Idiots", year: 2009 },
  { title: "Capernaum", year: 2018 },
  { title: "Joker", year: 2019 },
  { title: "Singin’ in the Rain", year: 1952 },
  { title: "Once Upon a Time in America", year: 1984 },
  { title: "Come and See", year: 1985 },
  { title: "Requiem for a Dream", year: 2000 },
  { title: "Return of the Jedi", year: 1983 },
  { title: "Toy Story 3", year: 2010 },
  { title: "The Hunt", year: 2012 },
  { title: "Ikiru", year: 1952 },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
  { title: "Incendies", year: 2010 },
  { title: "The Apartment", year: 1960 },
  { title: "Lawrence of Arabia", year: 1962 },
  { title: "2001: A Space Odyssey", year: 1968 },
  { title: "Reservoir Dogs", year: 1992 },
  { title: "Scarface", year: 1983 },
  { title: "Heat", year: 1995 },
  { title: "Double Indemnity", year: 1944 },
  { title: "Up", year: 2009 },
  { title: "North by Northwest", year: 1959 },
  { title: "M", year: 1931 },
  { title: "Full Metal Jacket", year: 1987 },
  { title: "Like Stars on Earth", year: 2007 },
  { title: "Citizen Kane", year: 1941 },
  { title: "Amélie", year: 2001 },
  { title: "Vertigo", year: 1958 },
  { title: "A Separation", year: 2011 },
  { title: "Die Hard", year: 1988 },
  { title: "To Kill a Mockingbird", year: 1962 },
  { title: "The Sting", year: 1973 },
  { title: "Indiana Jones and the Last Crusade", year: 1989 },
  { title: "A Clockwork Orange", year: 1971 },
  { title: "Metropolis", year: 1927 },
  { title: "Snatch", year: 2000 },
  { title: "1917", year: 2019 },
  { title: "L.A. Confidential", year: 1997 },
  { title: "Downfall", year: 2004 },
  { title: "Oppenheimer", year: 2023 },
  { title: "Bicycle Thieves", year: 1948 },
  { title: "Dangal", year: 2016 },
  { title: "The Wolf of Wall Street", year: 2013 },
  { title: "The Truman Show", year: 1998 },
  { title: "Green Book", year: 2018 },
  { title: "Batman Begins", year: 2005 },
  { title: "Hamilton", year: 2020 },
  { title: "Judgment at Nuremberg", year: 1961 },
  { title: "Shutter Island", year: 2010 },
  { title: "Taxi Driver", year: 1976 },
  { title: "For a Few Dollars More", year: 1965 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "Jurassic Park", year: 1993 },
  { title: "There Will Be Blood", year: 2007 },
  { title: "The Kid", year: 1921 },
  { title: "The Father", year: 2020 },
  { title: "All About Eve", year: 1950 },
  { title: "The Sixth Sense", year: 1999 },
  { title: "Ran", year: 1985 },
  { title: "Casino", year: 1995 },
  { title: "No Country for Old Men", year: 2007 },
  { title: "The Thing", year: 1982 },
  { title: "Top Gun: Maverick", year: 2022 },
  { title: "The Chaos Class Failed the Class", year: 1975 },
  { title: "Prisoners", year: 2013 },
  { title: "Pan’s Labyrinth", year: 2006 },
  { title: "Unforgiven", year: 1992 },
  { title: "Kill Bill: Vol. 1", year: 2003 },
  { title: "A Beautiful Mind", year: 2001 },
  { title: "The Treasure of the Sierra Madre", year: 1948 },
  { title: "Howl’s Moving Castle", year: 2004 },
  { title: "Finding Nemo", year: 2003 },
  { title: "Yojimbo", year: 1961 },
  { title: "The Great Escape", year: 1963 },
  { title: "Klaus", year: 2019 },
  { title: "The Best of Youth", year: 2003 },
  { title: "Monty Python and the Holy Grail", year: 1975 },
  { title: "The Elephant Man", year: 1980 },
  { title: "Dial M for Murder", year: 1954 },
  { title: "Gone with the Wind", year: 1939 },
  { title: "The Secret in Their Eyes", year: 2009 },
  { title: "Chinatown", year: 1974 },
  { title: "Lock, Stock and Two Smoking Barrels", year: 1998 },
  { title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle", year: 2025 },
  { title: "V for Vendetta", year: 2005 },
  { title: "Inside Out", year: 2015 },
  { title: "Rashomon", year: 1950 },
  { title: "Catch Me If You Can", year: 2002 },
  { title: "Three Billboards Outside Ebbing, Missouri", year: 2017 },
  { title: "Trainspotting", year: 1996 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "Harry Potter and the Deathly Hallows: Part 2", year: 2011 },
  { title: "Fargo", year: 1996 },
  { title: "Raging Bull", year: 1980 },
  { title: "Dead Poets Society", year: 1989 },
  { title: "Warrior", year: 2011 },
  { title: "The Wild Robot", year: 2024 },
  { title: "Barry Lyndon", year: 1975 },
  { title: "Ben-Hur", year: 1959 },
  { title: "Million Dollar Baby", year: 2004 },
  { title: "Mad Max: Fury Road", year: 2015 },
  { title: "Gran Torino", year: 2008 },
  { title: "My Neighbor Totoro", year: 1988 },
  { title: "Children of Heaven", year: 1997 },
  { title: "Hacksaw Ridge", year: 2016 },
  { title: "The Grand Budapest Hotel", year: 2014 },
  { title: "12 Years a Slave", year: 2013 },
  { title: "Before Sunrise", year: 1995 },
  { title: "Blade Runner", year: 1982 },
  { title: "Ratatouille", year: 2007 },
  { title: "Memories of Murder", year: 2003 },
  { title: "Spider-Man: No Way Home", year: 2021 },
  { title: "How to Train Your Dragon", year: 2010 },
  { title: "Gone Girl", year: 2014 },
  { title: "Monsters, Inc.", year: 2001 },
  { title: "Jaws", year: 1975 },
  { title: "In the Name of the Father", year: 1993 },
  { title: "Ford v Ferrari", year: 2019 },
  { title: "The Gold Rush", year: 1925 },
  { title: "Wild Tales", year: 2014 },
  { title: "Sherlock Jr.", year: 1924 },
  { title: "Mary and Max", year: 2009 },
  { title: "The Deer Hunter", year: 1978 },
  { title: "The Wages of Fear", year: 1953 },
  { title: "The General", year: 1926 },
  { title: "Logan", year: 2017 },
  { title: "Mr. Smith Goes to Washington", year: 1939 },
  { title: "Rocky", year: 1976 },
  { title: "On the Waterfront", year: 1954 },
  { title: "Tokyo Story", year: 1953 },
  { title: "Wild Strawberries", year: 1957 },
  { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003 },
  { title: "Spotlight", year: 2015 },
  { title: "The Third Man", year: 1949 },
  { title: "Jai Bhim", year: 2021 },
  { title: "La Haine", year: 1995 },
  { title: "Maharaja", year: 2024 },
  { title: "The Terminator", year: 1984 },
  { title: "The Big Lebowski", year: 1998 },
  { title: "The Sound of Music", year: 1965 },
  { title: "A Silent Voice: The Movie", year: 2016 },
  { title: "The Best Years of Our Lives", year: 1946 },
  { title: "The Seventh Seal", year: 1957 },
  { title: "Room", year: 2015 },
  { title: "Hotel Rwanda", year: 2004 },
  { title: "Platoon", year: 1986 },
  { title: "Before Sunset", year: 2004 },
  { title: "The Incredibles", year: 2004 },
  { title: "The Exorcist", year: 1973 },
  { title: "Hachi: A Dog’s Tale", year: 2009 },
  { title: "Chainsaw Man – The Movie: Reze Arc", year: 2025 },
  { title: "Rush", year: 2013 },
  { title: "The Wizard of Oz", year: 1939 },
  { title: "Stand by Me", year: 1986 },
  { title: "The Passion of Joan of Arc", year: 1928 },
  { title: "The Iron Giant", year: 1999 },
  { title: "My Father and My Son", year: 2005 },
  { title: "The Battle of Algiers", year: 1966 },
  { title: "The Handmaiden", year: 2016 },
  { title: "Network", year: 1976 },
  { title: "Gangs of Wasseypur – Part 1", year: 2012 },
  { title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", year: 2020 },
  { title: "Drishyam", year: 2015 },
  { title: "The Grapes of Wrath", year: 1940 },
  { title: "To Be or Not to Be", year: 1942 },
  { title: "Andhadhun", year: 2018 }
  ]
}

export const LETTERBOXD_TOP_250: CanonList = {
  id: 'letterboxd_top_250',
  title: "Letterboxd Top 250",
  shortTitle: "Official Top 250 Narrative Feature Films",
  sourceUrl: "https://letterboxd.com/dave/list/official-top-250-narrative-feature-films/",
  totalMovies: 250,
  movies: [
  { title: "Harakiri", year: 1962 },
  { title: "The Human Condition III: A Soldier’s Prayer", year: 1961 },
  { title: "12 Angry Men", year: 1957 },
  { title: "Come and See", year: 1985 },
  { title: "Seven Samurai", year: 1954 },
  { title: "High and Low", year: 1963 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "The Shawshank Redemption", year: 1994 },
  { title: "The Human Condition I: No Greater Love", year: 1959 },
  { title: "City of God", year: 2002 },
  { title: "Yi Yi", year: 2000 },
  { title: "The Lord of the Rings: The Return of the King", year: 2003 },
  { title: "Schindler’s List", year: 1993 },
  { title: "Parasite", year: 2019 },
  { title: "The Godfather", year: 1972 },
  { title: "Ikiru", year: 1952 },
  { title: "Ran", year: 1985 },
  { title: "The Good, the Bad and the Ugly", year: 1966 },
  { title: "La Haine", year: 1995 },
  { title: "A Brighter Summer Day", year: 1991 },
  { title: "Le Trou", year: 1960 },
  { title: "Cinema Paradiso", year: 1988 },
  { title: "The Dark Knight", year: 2008 },
  { title: "Autumn Sonata", year: 1978 },
  { title: "Grave of the Fireflies", year: 1988 },
  { title: "The Human Condition II: Road to Eternity", year: 1959 },
  { title: "Neon Genesis Evangelion: The End of Evangelion", year: 1997 },
  { title: "Woman in the Dunes", year: 1964 },
  { title: "There Will Be Blood", year: 2007 },
  { title: "GoodFellas", year: 1990 },
  { title: "The Cranes Are Flying", year: 1957 },
  { title: "Paths of Glory", year: 1957 },
  { title: "Spirited Away", year: 2001 },
  { title: "The Battle of Algiers", year: 1966 },
  { title: "Andrei Rublev", year: 1966 },
  { title: "Apocalypse Now", year: 1979 },
  { title: "Incendies", year: 2010 },
  { title: "The Apartment", year: 1960 },
  { title: "Tokyo Story", year: 1953 },
  { title: "Interstellar", year: 2014 },
  { title: "Sunset Boulevard", year: 1950 },
  { title: "I Am Cuba", year: 1964 },
  { title: "The Ascent", year: 1977 },
  { title: "The Passion of Joan of Arc", year: 1928 },
  { title: "Whiplash", year: 2014 },
  { title: "The Lord of the Rings: The Two Towers", year: 2002 },
  { title: "Fanny and Alexander", year: 1982 },
  { title: "It’s a Wonderful Life", year: 1946 },
  { title: "Mishima: A Life in Four Chapters", year: 1985 },
  { title: "Portrait of a Lady on Fire", year: 2019 },
  { title: "Sansho the Bailiff", year: 1954 },
  { title: "Memories of Murder", year: 2003 },
  { title: "Close-Up", year: 1990 },
  { title: "Spider-Man: Across the Spider-Verse", year: 2023 },
  { title: "The Red Shoes", year: 1948 },
  { title: "Stalker", year: 1979 },
  { title: "Barry Lyndon", year: 1975 },
  { title: "Nights of Cabiria", year: 1957 },
  { title: "Nobody Knows", year: 2004 },
  { title: "The Pianist", year: 2002 },
  { title: "Red Beard", year: 1965 },
  { title: "Do the Right Thing", year: 1989 },
  { title: "The Empire Strikes Back", year: 1980 },
  { title: "Spider-Man: Into the Spider-Verse", year: 2018 },
  { title: "A Woman Under the Influence", year: 1974 },
  { title: "Witness for the Prosecution", year: 1957 },
  { title: "Life Is Beautiful", year: 1997 },
  { title: "The Handmaiden", year: 2016 },
  { title: "Lawrence of Arabia", year: 1962 },
  { title: "Eternity and a Day", year: 1998 },
  { title: "Persona", year: 1966 },
  { title: "Princess Mononoke", year: 1997 },
  { title: "Once Upon a Time in the West", year: 1968 },
  { title: "Perfect Blue", year: 1997 },
  { title: "Love Exposure", year: 2008 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001 },
  { title: "Dune: Part Two", year: 2024 },
  { title: "In the Mood for Love", year: 2000 },
  { title: "Scenes from a Marriage", year: 1974 },
  { title: "Farewell My Concubine", year: 1993 },
  { title: "Satantango", year: 1994 },
  { title: "Paper Moon", year: 1973 },
  { title: "Paris, Texas", year: 1984 },
  { title: "Sherlock Jr.", year: 1924 },
  { title: "Where Is the Friend’s House?", year: 1987 },
  { title: "An Elephant Sitting Still", year: 2018 },
  { title: "War and Peace", year: 1967 },
  { title: "Oldboy", year: 2003 },
  { title: "A Separation", year: 2011 },
  { title: "It’s Such a Beautiful Day", year: 2012 },
  { title: "Rear Window", year: 1954 },
  { title: "Good Will Hunting", year: 1997 },
  { title: "One Flew Over the Cuckoo’s Nest", year: 1975 },
  { title: "Apur Sansar", year: 1959 },
  { title: "Se7en", year: 1995 },
  { title: "Chainsaw Man – The Movie: Reze Arc", year: 2025 },
  { title: "Landscape in the Mist", year: 1988 },
  { title: "Inglourious Basterds", year: 2009 },
  { title: "Army of Shadows", year: 1969 },
  { title: "All About Eve", year: 1950 },
  { title: "Ordet", year: 1955 },
  { title: "Howl’s Moving Castle", year: 2004 },
  { title: "The Wages of Fear", year: 1953 },
  { title: "The Thing", year: 1982 },
  { title: "Swing Girls", year: 2004 },
  { title: "Amadeus", year: 1984 },
  { title: "Z", year: 1969 },
  { title: "A Man Escaped", year: 1956 },
  { title: "Central Station", year: 1998 },
  { title: "Singin’ in the Rain", year: 1952 },
  { title: "How to Make Millions Before Grandma Dies", year: 2024 },
  { title: "All That Jazz", year: 1979 },
  { title: "Judgment at Nuremberg", year: 1961 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "Still Walking", year: 2008 },
  { title: "Three Colours: Red", year: 1994 },
  { title: "Late Spring", year: 1949 },
  { title: "Raise the Red Lantern", year: 1991 },
  { title: "Dead Poets Society", year: 1989 },
  { title: "I’m Still Here", year: 2024 },
  { title: "A Special Day", year: 1977 },
  { title: "The Departed", year: 2006 },
  { title: "City Lights", year: 1931 },
  { title: "Wild Strawberries", year: 1957 },
  { title: "To Be or Not to Be", year: 1942 },
  { title: "The Seventh Seal", year: 1957 },
  { title: "Monster", year: 2023 },
  { title: "The Voice of Hind Rajab", year: 2025 },
  { title: "The Great Dictator", year: 1940 },
  { title: "Funeral Parade of Roses", year: 1969 },
  { title: "Brief Encounter", year: 1945 },
  { title: "Mirror", year: 1975 },
  { title: "Taste of Cherry", year: 1997 },
  { title: "Das Boot", year: 1981 },
  { title: "Django Unchained", year: 2012 },
  { title: "Before Sunset", year: 2004 },
  { title: "The Young Girls of Rochefort", year: 1967 },
  { title: "Pather Panchali", year: 1955 },
  { title: "Prisoners", year: 2013 },
  { title: "Rocco and His Brothers", year: 1960 },
  { title: "No Country for Old Men", year: 2007 },
  { title: "Mommy", year: 2014 },
  { title: "Tampopo", year: 1985 },
  { title: "The Celebration", year: 1998 },
  { title: "Psycho", year: 1960 },
  { title: "The Best of Youth", year: 2003 },
  { title: "Dog Day Afternoon", year: 1975 },
  { title: "Wings of Desire", year: 1987 },
  { title: "Perfect Days", year: 2023 },
  { title: "The 400 Blows", year: 1959 },
  { title: "Twin Peaks: Fire Walk with Me", year: 1992 },
  { title: "Underground", year: 1995 },
  { title: "Before Sunrise", year: 1995 },
  { title: "Werckmeister Harmonies", year: 2000 },
  { title: "Shoplifters", year: 2018 },
  { title: "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb", year: 1964 },
  { title: "Yojimbo", year: 1961 },
  { title: "Children of Men", year: 2006 },
  { title: "Sing Sing", year: 2023 },
  { title: "Chinatown", year: 1974 },
  { title: "Heat", year: 1995 },
  { title: "M", year: 1931 },
  { title: "Fantastic Mr. Fox", year: 2009 },
  { title: "Marty Supreme", year: 2025 },
  { title: "The Treasure of the Sierra Madre", year: 1948 },
  { title: "Opening Night", year: 1977 },
  { title: "The Sacrifice", year: 1986 },
  { title: "Bicycle Thieves", year: 1948 },
  { title: "The Cremator", year: 1969 },
  { title: "The Lives of Others", year: 2006 },
  { title: "Terminator 2: Judgment Day", year: 1991 },
  { title: "The Father", year: 2020 },
  { title: "The Elephant Man", year: 1980 },
  { title: "La Notte", year: 1961 },
  { title: "One Battle After Another", year: 2025 },
  { title: "Dersu Uzala", year: 1975 },
  { title: "Children of Paradise", year: 1945 },
  { title: "Samurai Rebellion", year: 1967 },
  { title: "The Hunt", year: 2012 },
  { title: "Evangelion: 3.0+1.0 Thrice Upon a Time", year: 2021 },
  { title: "Secrets & Lies", year: 1996 },
  { title: "Chungking Express", year: 1994 },
  { title: "Nostalgia", year: 1983 },
  { title: "Akira", year: 1988 },
  { title: "The Man Who Shot Liberty Valance", year: 1962 },
  { title: "8½", year: 1963 },
  { title: "Puella Magi Madoka Magica the Movie Part III: Rebellion", year: 2013 },
  { title: "Casablanca", year: 1942 },
  { title: "Life, and Nothing More…", year: 1992 },
  { title: "Azur & Asmar: The Princes’ Quest", year: 2006 },
  { title: "The Iron Giant", year: 1999 },
  { title: "Malcolm X", year: 1992 },
  { title: "Throne of Blood", year: 1957 },
  { title: "Ace in the Hole", year: 1951 },
  { title: "Fight Club", year: 1999 },
  { title: "Cure", year: 1997 },
  { title: "The Green Mile", year: 1999 },
  { title: "The Prestige", year: 2006 },
  { title: "Some Like It Hot", year: 1959 },
  { title: "La Dolce Vita", year: 1960 },
  { title: "Who’s Afraid of Virginia Woolf?", year: 1966 },
  { title: "Look Back", year: 2024 },
  { title: "We All Loved Each Other So Much", year: 1974 },
  { title: "Jeanne Dielman, 23, quai du Commerce, 1080 Bruxelles", year: 1975 },
  { title: "Fail Safe", year: 1964 },
  { title: "Ritual", year: 2000 },
  { title: "Rififi", year: 1955 },
  { title: "Ugetsu", year: 1953 },
  { title: "Modern Times", year: 1936 },
  { title: "Network", year: 1976 },
  { title: "Mary and Max", year: 2009 },
  { title: "A Matter of Life and Death", year: 1946 },
  { title: "Sorcerer", year: 1977 },
  { title: "2001: A Space Odyssey", year: 1968 },
  { title: "Mulholland Drive", year: 2001 },
  { title: "The Night of the Hunter", year: 1955 },
  { title: "Song of the Sea", year: 2014 },
  { title: "Double Indemnity", year: 1944 },
  { title: "Aparajito", year: 1956 },
  { title: "The Tale of The Princess Kaguya", year: 2013 },
  { title: "Everything Everywhere All at Once", year: 2022 },
  { title: "Interstella 5555: The 5tory of the 5ecret 5tar 5ystem", year: 2003 },
  { title: "Umberto D.", year: 1952 },
  { title: "Alien", year: 1979 },
  { title: "Winter Light", year: 1963 },
  { title: "Saving Private Ryan", year: 1998 },
  { title: "Il Sorpasso", year: 1962 },
  { title: "Metropolis", year: 1927 },
  { title: "Pulp Fiction", year: 1994 },
  { title: "The First Slam Dunk", year: 2022 },
  { title: "The Face of Another", year: 1966 },
  { title: "The Holdovers", year: 2023 },
  { title: "Kes", year: 1969 },
  { title: "The Third Man", year: 1949 },
  { title: "Sweet Smell of Success", year: 1957 },
  { title: "Anatomy of a Murder", year: 1959 },
  { title: "The Grand Budapest Hotel", year: 2014 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "The Best Years of Our Lives", year: 1946 },
  { title: "Marcel the Shell with Shoes On", year: 2021 },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004 },
  { title: "Tokyo Godfathers", year: 2003 },
  { title: "4 Months, 3 Weeks and 2 Days", year: 2007 },
  { title: "The Disappearance of Haruhi Suzumiya", year: 2010 },
  { title: "Kwaidan", year: 1964 },
  { title: "The King of Comedy", year: 1982 },
  { title: "Napoleon", year: 1927 },
  { title: "Quo Vadis, Aida?", year: 2020 },
  { title: "A Moment of Innocence", year: 1996 },
  { title: "Son of the White Mare", year: 1981 }
  ]
}

export const OSCAR_BEST_PICTURE: CanonList = {
  id: 'oscar_best_picture',
  title: "Oscar Best Picture Winners",
  shortTitle: "Oscar Best Picture Winners",
  sourceUrl: "https://letterboxd.com/oscars/list/oscar-winning-films-best-picture/",
  totalMovies: 97,
  movies: [
  { title: "Anora", year: 2024 },
  { title: "Oppenheimer", year: 2023 },
  { title: "Everything Everywhere All at Once", year: 2022 },
  { title: "CODA", year: 2021 },
  { title: "Nomadland", year: 2020 },
  { title: "Parasite", year: 2019 },
  { title: "Green Book", year: 2018 },
  { title: "The Shape of Water", year: 2017 },
  { title: "Moonlight", year: 2016 },
  { title: "Spotlight", year: 2015 },
  { title: "Birdman or (The Unexpected Virtue of Ignorance)", year: 2014 },
  { title: "12 Years a Slave", year: 2013 },
  { title: "Argo", year: 2012 },
  { title: "The Artist", year: 2011 },
  { title: "The King’s Speech", year: 2010 },
  { title: "The Hurt Locker", year: 2008 },
  { title: "Slumdog Millionaire", year: 2008 },
  { title: "No Country for Old Men", year: 2007 },
  { title: "The Departed", year: 2006 },
  { title: "Crash", year: 2004 },
  { title: "Million Dollar Baby", year: 2004 },
  { title: "The Lord of the Rings: The Return of the King", year: 2003 },
  { title: "Chicago", year: 2002 },
  { title: "A Beautiful Mind", year: 2001 },
  { title: "Gladiator", year: 2000 },
  { title: "American Beauty", year: 1999 },
  { title: "Shakespeare in Love", year: 1998 },
  { title: "Titanic", year: 1997 },
  { title: "The English Patient", year: 1996 },
  { title: "Braveheart", year: 1995 },
  { title: "Forrest Gump", year: 1994 },
  { title: "Schindler’s List", year: 1993 },
  { title: "Unforgiven", year: 1992 },
  { title: "The Silence of the Lambs", year: 1991 },
  { title: "Dances with Wolves", year: 1990 },
  { title: "Driving Miss Daisy", year: 1989 },
  { title: "Rain Man", year: 1988 },
  { title: "The Last Emperor", year: 1987 },
  { title: "Platoon", year: 1986 },
  { title: "Out of Africa", year: 1985 },
  { title: "Amadeus", year: 1984 },
  { title: "Terms of Endearment", year: 1983 },
  { title: "Gandhi", year: 1982 },
  { title: "Chariots of Fire", year: 1981 },
  { title: "Ordinary People", year: 1980 },
  { title: "Kramer vs. Kramer", year: 1979 },
  { title: "The Deer Hunter", year: 1978 },
  { title: "Annie Hall", year: 1977 },
  { title: "Rocky", year: 1976 },
  { title: "One Flew Over the Cuckoo’s Nest", year: 1975 },
  { title: "The Godfather Part II", year: 1974 },
  { title: "The Sting", year: 1973 },
  { title: "The Godfather", year: 1972 },
  { title: "The French Connection", year: 1971 },
  { title: "Patton", year: 1970 },
  { title: "Midnight Cowboy", year: 1969 },
  { title: "Oliver!", year: 1968 },
  { title: "In the Heat of the Night", year: 1967 },
  { title: "A Man for All Seasons", year: 1966 },
  { title: "The Sound of Music", year: 1965 },
  { title: "My Fair Lady", year: 1964 },
  { title: "Tom Jones", year: 1963 },
  { title: "Lawrence of Arabia", year: 1962 },
  { title: "West Side Story", year: 1961 },
  { title: "The Apartment", year: 1960 },
  { title: "Ben-Hur", year: 1959 },
  { title: "Gigi", year: 1958 },
  { title: "The Bridge on the River Kwai", year: 1957 },
  { title: "Around the World in 80 Days", year: 1956 },
  { title: "Marty", year: 1955 },
  { title: "On the Waterfront", year: 1954 },
  { title: "From Here to Eternity", year: 1953 },
  { title: "The Greatest Show on Earth", year: 1952 },
  { title: "An American in Paris", year: 1951 },
  { title: "All About Eve", year: 1950 },
  { title: "All the King’s Men", year: 1949 },
  { title: "Hamlet", year: 1948 },
  { title: "Gentleman’s Agreement", year: 1947 },
  { title: "The Best Years of Our Lives", year: 1946 },
  { title: "The Lost Weekend", year: 1945 },
  { title: "Going My Way", year: 1944 },
  { title: "Casablanca", year: 1942 },
  { title: "Mrs. Miniver", year: 1942 },
  { title: "How Green Was My Valley", year: 1941 },
  { title: "Rebecca", year: 1940 },
  { title: "Gone with the Wind", year: 1939 },
  { title: "You Can’t Take It with You", year: 1938 },
  { title: "The Life of Emile Zola", year: 1937 },
  { title: "The Great Ziegfeld", year: 1936 },
  { title: "Mutiny on the Bounty", year: 1935 },
  { title: "It Happened One Night", year: 1934 },
  { title: "Cavalcade", year: 1933 },
  { title: "Grand Hotel", year: 1932 },
  { title: "Cimarron", year: 1931 },
  { title: "All Quiet on the Western Front", year: 1930 },
  { title: "The Broadway Melody", year: 1929 },
  { title: "Wings", year: 1927 }
  ]
}

export const ALL_CANON_LISTS: CanonList[] = [
  AFI,
  CANNES_PALME,
  IMDB_TOP_250,
  LETTERBOXD_TOP_250,
  OSCAR_BEST_PICTURE
]

export const CANON_STATS = {
  totalLists: 5,
  totalMovies: 800,
  lists: {
    'afi': 100,
    'cannes_palme': 103,
    'imdb_top_250': 250,
    'letterboxd_top_250': 250,
    'oscar_best_picture': 97
  }
}
